// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	user "douyin-project/microservice/user/rpc/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FindByName(ctx context.Context, req *user.FindByNameRequest, callOptions ...callopt.Option) (r *user.FindByNameResp, err error)
	FindByUserId(ctx context.Context, req *user.FindByUserIdRequest, callOptions ...callopt.Option) (r *user.FindByUserIdResp, err error)
	Insert(ctx context.Context, req *user.InsertRequest, callOptions ...callopt.Option) (r *user.InsertResp, err error)
	Update(ctx context.Context, req *user.UpdateRequest, callOptions ...callopt.Option) (r *user.UpdateResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) FindByName(ctx context.Context, req *user.FindByNameRequest, callOptions ...callopt.Option) (r *user.FindByNameResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindByName(ctx, req)
}

func (p *kUserServiceClient) FindByUserId(ctx context.Context, req *user.FindByUserIdRequest, callOptions ...callopt.Option) (r *user.FindByUserIdResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindByUserId(ctx, req)
}

func (p *kUserServiceClient) Insert(ctx context.Context, req *user.InsertRequest, callOptions ...callopt.Option) (r *user.InsertResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Insert(ctx, req)
}

func (p *kUserServiceClient) Update(ctx context.Context, req *user.UpdateRequest, callOptions ...callopt.Option) (r *user.UpdateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Update(ctx, req)
}
