// Code generated by Kitex v0.4.4. DO NOT EDIT.

package commentservice

import (
	"context"
	comment "douyin-project/microservice/comment/rpc/kitex_gen/comment"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return commentServiceServiceInfo
}

var commentServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "CommentService"
	handlerType := (*comment.CommentService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Insert":                      kitex.NewMethodInfo(insertHandler, newCommentServiceInsertArgs, newCommentServiceInsertResult, false),
		"Delete":                      kitex.NewMethodInfo(deleteHandler, newCommentServiceDeleteArgs, newCommentServiceDeleteResult, false),
		"FindByVideoId":               kitex.NewMethodInfo(findByVideoIdHandler, newCommentServiceFindByVideoIdArgs, newCommentServiceFindByVideoIdResult, false),
		"FindCommentByVideoIdLimit30": kitex.NewMethodInfo(findCommentByVideoIdLimit30Handler, newCommentServiceFindCommentByVideoIdLimit30Args, newCommentServiceFindCommentByVideoIdLimit30Result, false),
	}
	extra := map[string]interface{}{
		"PackageName": "comment",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func insertHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*comment.CommentServiceInsertArgs)
	realResult := result.(*comment.CommentServiceInsertResult)
	success, err := handler.(comment.CommentService).Insert(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommentServiceInsertArgs() interface{} {
	return comment.NewCommentServiceInsertArgs()
}

func newCommentServiceInsertResult() interface{} {
	return comment.NewCommentServiceInsertResult()
}

func deleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*comment.CommentServiceDeleteArgs)
	realResult := result.(*comment.CommentServiceDeleteResult)
	success, err := handler.(comment.CommentService).Delete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommentServiceDeleteArgs() interface{} {
	return comment.NewCommentServiceDeleteArgs()
}

func newCommentServiceDeleteResult() interface{} {
	return comment.NewCommentServiceDeleteResult()
}

func findByVideoIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*comment.CommentServiceFindByVideoIdArgs)
	realResult := result.(*comment.CommentServiceFindByVideoIdResult)
	success, err := handler.(comment.CommentService).FindByVideoId(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommentServiceFindByVideoIdArgs() interface{} {
	return comment.NewCommentServiceFindByVideoIdArgs()
}

func newCommentServiceFindByVideoIdResult() interface{} {
	return comment.NewCommentServiceFindByVideoIdResult()
}

func findCommentByVideoIdLimit30Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*comment.CommentServiceFindCommentByVideoIdLimit30Args)
	realResult := result.(*comment.CommentServiceFindCommentByVideoIdLimit30Result)
	success, err := handler.(comment.CommentService).FindCommentByVideoIdLimit30(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCommentServiceFindCommentByVideoIdLimit30Args() interface{} {
	return comment.NewCommentServiceFindCommentByVideoIdLimit30Args()
}

func newCommentServiceFindCommentByVideoIdLimit30Result() interface{} {
	return comment.NewCommentServiceFindCommentByVideoIdLimit30Result()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Insert(ctx context.Context, req *comment.InsertReq) (r *comment.InsertResp, err error) {
	var _args comment.CommentServiceInsertArgs
	_args.Req = req
	var _result comment.CommentServiceInsertResult
	if err = p.c.Call(ctx, "Insert", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Delete(ctx context.Context, req *comment.DeleteReq) (r *comment.DeleteResp, err error) {
	var _args comment.CommentServiceDeleteArgs
	_args.Req = req
	var _result comment.CommentServiceDeleteResult
	if err = p.c.Call(ctx, "Delete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FindByVideoId(ctx context.Context, req *comment.FindByVideoIdReq) (r *comment.FindByVideoIdResp, err error) {
	var _args comment.CommentServiceFindByVideoIdArgs
	_args.Req = req
	var _result comment.CommentServiceFindByVideoIdResult
	if err = p.c.Call(ctx, "FindByVideoId", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FindCommentByVideoIdLimit30(ctx context.Context, req *comment.FindCommentByVideoIdLimit30Req) (r *comment.FindCommentByVideoIdLimit30Resp, err error) {
	var _args comment.CommentServiceFindCommentByVideoIdLimit30Args
	_args.Req = req
	var _result comment.CommentServiceFindCommentByVideoIdLimit30Result
	if err = p.c.Call(ctx, "FindCommentByVideoIdLimit30", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
